### ISSUE TITLE
Issues with the starter

### ISSUE THREAD

**Issue by jonniebigodes** [fabianunger/gatsby-starter-redux-storybook#2]
@fabianunger i saw that you've submitted the Starter to Gatstby starters and i decided to take out for a spin. With that in mind there's some items that need to be addressed that will greatly improve usability.

I'm going to break this issue into 2 parts. One regarding general usability, the other Storybook oriented.

- Update the readme with some instructions on how to create a site with the starter and how to use it. After creating a site with this starter i instinctively tried to run Storybook with `yarn storybook` / `npm run storybook` and i have a error:
```bash
error Command "storybook" not found.
```
- Add a link to the storybook documentation and possibly to the Gatsby documentation for Storybook would be a nice touch.
- If you can remove the concurrent package, to allow the user to options. Also introduce back the `develop` script. Me and others that use gatsby, or newcomers that use this and follow the documentation will instinctively default to `develop`. 
- Also other scripts need a bit of simplification as to avoid extraneous work.
- Add a description of what's inside the starter, so that the user will know where each piece is where. 
- Deploy the Storybook somewhere so that the user will see it in action.

Storybook wise:

- When i created my test site it bumped my versions of Storybook. I works with the current configuration but as per version 5.3 there are some significant changes how Storybook handles the configuration. For now it's backwards compatible to some extent, but we can't assume it will be in the future. As per a recent conversation with one of the Storybook maintainers their pushing for their new config system as much as possible to allow early adoption as much as possible.
- Also if you can move the stories to CSF ( Component Story Format), once again the current usage is allowed. But we can't be sure in the future. As once again with conversation with the Storybook maintainers they're pushing for CSF for simplicity.

As a side note, as it might help you a bit, there's currently a pr addressing how Storybook is added to Gatsby and a issue that sparked the whole initiative to update the documentation. More specifically [this](https://github.com/gatsbyjs/gatsby/issues/20624). If you look at my answer you'll get a clear picture on how you can make the changes to Storybook with the new version allowing users to easily integrate both frameworks.

If you're willing to address this issue, i think it will greatly improve usability and probably allow having issues in both repos that could easily solved. 

Also on a particular note, if you address this i'm more than glad to spread this out for discoverability and with some luck adoption. Sounds good to you? 

Feel free to provide feedback

**Comment by fabianunger** [comment]
@jonniebigodes Thanks for the feedback, will do!

**Comment by fabianunger** [comment]
@jonniebigodes should be all fine now, if you have any more feedback or input, feel free to open the issue again!
